// Walk audit — is the engine choosing OSI walks too often because our walk
// times are too low?
//
// Three questions, three sections:
//
//   1. WHICH OSI PAIRS ACTUALLY MATTER. 39 pairs are defined but only a handful
//      appear in published optima. Verify those against TfL, ignore the rest.
//   2. INTERCHANGE DODGING. A walk whose destination line was already available
//      at the station you walked FROM isn't covering distance, it's avoiding an
//      in-station change. Sometimes right (Canary Wharf's 11-min Jubilee->DLR
//      change), usually not. The margin is what tells them apart, and the margin
//      is what a too-low walk time corrupts.
//   3. SENSITIVITY SWEEP. Add N minutes to every OSI walk and see how many
//      optima still route through one. If a +2 correction removes most of them,
//      the walk times were the problem. If they survive +5, something else is.
//
// Usage:
//   node walk-audit.mjs                 # audit the working tree
//   TUBED_HTML=backups/x.bak node walk-audit.mjs
//
// Ground truth (Douglas, TfL journey planner, 2026-08-17):
//   Canary Wharf <-> Heron Quays          ours 3, TfL 9
//   Shepherd's Bush <-> SB (Overground)   ours 4, TfL 7
//   Shadwell <-> Shadwell (Overground)    6 (re-measured 2026-08-19; was 2)

import { readFileSync, writeFileSync, mkdtempSync } from 'fs';
import { tmpdir } from 'os';
import path from 'path';
import { loadEngine, ROOT } from './tests/lib/engine.mjs';

const SRC = process.env.TUBED_HTML || 'index.html';
const html = readFileSync(path.join(ROOT, SRC), 'utf8');
const work = mkdtempSync(path.join(tmpdir(), 'walkaudit-'));

// Build a variant with every OSI walk inflated by `delta` minutes.
//
// MUST patch the OSI_PAIRS LITERAL, not osiTime(). buildGraph reads p.aToB /
// p.bToA straight off the literal (see addOsiWalkEdges call sites), so an
// osiTime override changes how a walk is PRICED without changing the graph the
// search explores. That hybrid quietly understates the effect: on 2026-08-18 it
// predicted 12/400 walk-optima where editing the data gave 14/400, and it missed
// a pair surfacing entirely. Same trap as auditing puzzle-lookup.json instead of
// the draw pool — measure the thing you're actually going to change.
const BLOCK = /const OSI_PAIRS = \[[\s\S]*?\n\];/;
function engineWithDelta(delta) {
  if (delta === 0) return loadEngine(SRC);
  const m = html.match(BLOCK);
  if (!m) {
    console.error('FATAL: could not find the OSI_PAIRS literal. Did its shape change?');
    process.exit(1);
  }
  let n = 0;
  const bumped = m[0].replace(/(aToB|bToA):\s*(\d+)/g, (_, k, v) => {
    n++; return `${k}:${Number(v) + delta}`;
  });
  if (n === 0) { console.error('FATAL: matched OSI_PAIRS but replaced no values.'); process.exit(1); }
  const p = path.join(work, `d${delta}.html`);
  writeFileSync(p, html.replace(BLOCK, bumped));
  return loadEngine(p);
}

// CORPUS. Deliberately NOT puzzle-lookup.json — that file was generated by
// whichever engine was live at the time, so auditing it measures the old rule's
// output, not this engine's tendency. (The shipped lookup was built under the
// walk-free rule and contains zero walks by construction; auditing it reports a
// tidy 0% that means nothing.) Sample the actual draw pool instead, the same way
// the generator does, so the question being answered is "how often does THIS
// engine reach for a walk".
const SAMPLE = Number(process.env.SAMPLE || 400);
const T0 = engineWithDelta(0);
const g0 = T0.buildGraph();
const pool = T0.PUZZLE_STATIONS;
const rng = T0.seededRng(20260817);
const seen = new Set();
const upcoming = [];
let guard = 0;
while (upcoming.length < SAMPLE && guard++ < 40000) {
  const a = pool[Math.floor(rng() * pool.length)];
  const b = pool[Math.floor(rng() * pool.length)];
  if (a === b) continue;
  const k = a < b ? `${a}|${b}` : `${b}|${a}`;
  if (seen.has(k)) continue;
  seen.add(k);
  if (!T0.requiresChange(a, b)) continue;
  upcoming.push({ start: a, end: b, date: '-', mode: 'pool' });
}
console.log(`corpus: ${upcoming.length} sampled pool pairs (SAMPLE=${SAMPLE} to change)`);

// ── 1. Which OSI pairs appear in published optima ────────────────────────────
const usage = new Map();
const dodges = [];
let walkOptima = 0;

for (const inst of upcoming) {
  const routes = T0.dijkstra(g0, inst.start, inst.end);
  const opt = T0.pickOptimal(routes, {});
  if (!opt) continue;
  let counted = false;
  for (let i = 0; i < opt.legs.length; i++) {
    const leg = opt.legs[i];
    if (leg.line !== 'Walk') continue;
    if (!counted) { walkOptima++; counted = true; }
    const key = [leg.from, leg.to].sort().join(' <-> ');
    const u = usage.get(key) || { n: 0, mins: leg.mins };
    u.n++; usage.set(key, u);

    // Dodge check
    const next = opt.legs[i + 1], prev = opt.legs[i - 1];
    if (!next || !prev) continue;
    const nextDl = T0.displayLine(next.branchLine || next.line);
    const prevDl = T0.displayLine(prev.branchLine || prev.line);
    if (!T0.linesAtStation(leg.from).map(T0.displayLine).includes(nextDl)) continue;
    const inPlace = T0.interchangeTime(leg.from, prevDl, nextDl);
    dodges.push({ date: inst.date, mode: inst.mode, pair: `${inst.start} -> ${inst.end}`,
      at: leg.from, to: leg.to, walk: leg.mins, inPlace, line: nextDl,
      margin: inPlace == null ? null : inPlace - leg.mins });
  }
}

console.log(`\n═══ 1. OSI pairs used by published optima (${upcoming.length} upcoming instances) ═══`);
console.log(`${walkOptima} optima contain a walk (${(100 * walkOptima / upcoming.length).toFixed(1)}%)\n`);
console.log('  uses  ours  pair');
[...usage.entries()].sort((a, b) => b[1].n - a[1].n).forEach(([k, v]) =>
  console.log(`  ${String(v.n).padStart(4)}  ${String(v.mins).padStart(4)}  ${k}`));
console.log('\n  ^ THIS is the list to check against TfL. The other OSI pairs never surface.');

// ── 2. Interchange dodging ───────────────────────────────────────────────────
console.log(`\n═══ 2. Walks that dodge an in-place change ═══`);
console.log(`A walk to board a line that was ALREADY at the station you left.`);
console.log(`margin = what the in-station change would have cost, minus the walk.`);
console.log(`Small margin = arbitrage the walk time is buying. Large = genuinely worth walking.\n`);
if (!dodges.length) console.log('  none');
else {
  dodges.sort((a, b) => (a.margin ?? 99) - (b.margin ?? 99));
  console.log('  margin  walk  in-place  at                     line          puzzle');
  for (const d of dodges.slice(0, 25)) {
    console.log(`  ${String(d.margin ?? '?').padStart(6)}  ${String(d.walk).padStart(4)}  ${String(d.inPlace ?? '?').padStart(8)}  ${d.at.padEnd(21)}  ${d.line.padEnd(12)}  ${d.date} ${d.mode}`);
  }
  const marginal = dodges.filter(d => d.margin != null && d.margin <= 3).length;
  console.log(`\n  ${marginal} of ${dodges.length} have a margin <= 3 min — those flip if the walk time is 3 min too low.`);
}

// ── 3. Sensitivity sweep ─────────────────────────────────────────────────────
console.log(`\n═══ 3. Sensitivity: add N minutes to every OSI walk ═══`);
console.log(`If our walk times are systematically low, walk-optima should thin out fast.\n`);
console.log('  +N   optima with a walk   dodging walks');
for (const delta of [0, 1, 2, 3, 4, 5]) {
  const T = engineWithDelta(delta);
  const g = T.buildGraph();
  let w = 0, d = 0;
  for (const inst of upcoming) {
    const routes = T.dijkstra(g, inst.start, inst.end);
    const opt = T.pickOptimal(routes, {});
    if (!opt) continue;
    let counted = false;
    for (let i = 0; i < opt.legs.length; i++) {
      const leg = opt.legs[i];
      if (leg.line !== 'Walk') continue;
      if (!counted) { w++; counted = true; }
      const next = opt.legs[i + 1];
      if (next && T.linesAtStation(leg.from).map(T.displayLine)
        .includes(T.displayLine(next.branchLine || next.line))) d++;
    }
  }
  console.log(`  +${delta}   ${String(w).padStart(3)} / ${upcoming.length}  (${String((100*w/upcoming.length).toFixed(1)).padStart(4)}%)      ${d}`);
}
console.log();
