"""Tests for writer.py — JS output formatting and in-place HTML replacement."""

import tempfile
from pathlib import Path

import pytest

from build_interchanges import writer


def test_format_interchange_block_basic():
    out = writer.format_interchange_block({
        'Acton Town': {'District|Piccadilly': 2},
        'Bond Street': {'Central|Jubilee': 4},
    }, source_note='test')
    # All keys use double quotes.
    assert '"Acton Town"' in out
    assert '"Bond Street"' in out
    assert '"District|Piccadilly": 2,' in out
    # Stations are sorted alphabetically.
    assert out.index('Acton Town') < out.index('Bond Street')


def test_format_interchange_block_escapes_special_chars():
    out = writer.format_interchange_block({
        "Earl's Court": {'District|Piccadilly': 3},
    })
    # Apostrophe goes through double quotes — no backslash needed.
    assert '"Earl\'s Court"' in out
    # Make sure no malformed escaping happens.
    assert "\\'" not in out


def test_format_interchange_block_omits_empty_stations():
    out = writer.format_interchange_block({
        'Acton Town': {'District|Piccadilly': 2},
        'Empty Station': {},
    })
    assert 'Acton Town' in out
    assert 'Empty Station' not in out


def test_replace_in_html_preserves_surroundings():
    html_before = (
        'const PLATFORM_GROUPS = { whatever };\n'
        '\n'
        'const INTERCHANGE_MINS = {\n'
        "  'Old Station': {\n"
        "    'A|B': 5,\n"
        '  },\n'
        '};\n'
        '\n'
        'const OSI_PAIRS = [];\n'
    )
    with tempfile.NamedTemporaryFile(suffix='.html', mode='w',
                                     delete=False, encoding='utf-8') as f:
        f.write(html_before)
        path = Path(f.name)

    try:
        writer.replace_in_html(path, {'New Station': {'X|Y': 3}})
        result = path.read_text(encoding='utf-8')
        # Surroundings preserved.
        assert 'PLATFORM_GROUPS' in result
        assert 'OSI_PAIRS' in result
        # Old block gone.
        assert 'Old Station' not in result
        # New block in place.
        assert 'New Station' in result
        assert '"X|Y": 3' in result
    finally:
        path.unlink()


def test_replace_in_html_raises_when_block_missing():
    with tempfile.NamedTemporaryFile(suffix='.html', mode='w',
                                     delete=False, encoding='utf-8') as f:
        f.write('const SOMETHING_ELSE = {};\n')
        path = Path(f.name)
    try:
        with pytest.raises(ValueError):
            writer.replace_in_html(path, {})
    finally:
        path.unlink()


def test_replace_in_html_is_idempotent():
    """Re-running replace_in_html on a file that already has a generated
    header block should NOT pile up duplicate headers."""
    html_initial = (
        'const PLATFORM_GROUPS = {};\n'
        '\n'
        'const INTERCHANGE_MINS = {\n'
        "  'X': { 'A|B': 1 },\n"
        '};\n'
        '\n'
        'const OSI_PAIRS = [];\n'
    )
    with tempfile.NamedTemporaryFile(suffix='.html', mode='w',
                                     delete=False, encoding='utf-8') as f:
        f.write(html_initial)
        path = Path(f.name)
    try:
        writer.replace_in_html(path, {'Y': {'C|D': 2}})
        writer.replace_in_html(path, {'Z': {'E|F': 3}})
        result = path.read_text(encoding='utf-8')
        # Exactly one header block, not two.
        assert result.count('Auto-generated by build_interchanges') == 1
        # Final station is Z.
        assert 'Z' in result
        assert 'Y' not in result
    finally:
        path.unlink()


def test_format_round_trip_with_game_data_parser():
    """The output of format_interchange_block must parse back to the same
    dict via game_data.parse_interchange_mins."""
    from build_interchanges import game_data

    original = {
        'Bond Street': {'Central|Elizabeth': 8, 'Central|Jubilee': 5},
        "Earl's Court": {'District|Piccadilly': 3},
        "St. James's Park": {'Circle|District': 4},
    }
    js = writer.format_interchange_block(original)
    parsed = game_data.parse_interchange_mins(js)
    assert parsed == original
