"""Smoke tests for the live index.html.

These guard against accidents in the apply pipeline:
  * The INTERCHANGE_MINS block must still parse as a JS object literal.
  * Expected stations and pairs must still be present.
  * The generated header must appear exactly once (not piled up by
    repeated --apply runs).

Run alongside the other Python tests: `python3 -m pytest tests/python/`.
"""

import re
import subprocess
from pathlib import Path

import pytest

from build_interchanges import game_data


ROOT = Path(__file__).parent.parent.parent
INDEX_HTML = ROOT / 'index.html'


def _skip_if_no_index():
    if not INDEX_HTML.exists():
        pytest.skip('index.html not present')


def test_interchange_block_parses_as_js():
    """Use node to parse the const INTERCHANGE_MINS block. Catches
    syntax errors, unescaped quotes, broken commas, etc."""
    _skip_if_no_index()
    # Skip if node isn't available (e.g. CI image without it).
    node = subprocess.run(['which', 'node'], capture_output=True, text=True)
    if node.returncode != 0:
        pytest.skip('node not available')

    script = '''
        const fs = require('fs');
        const html = fs.readFileSync(process.argv[1], 'utf-8');
        const m = html.match(/const INTERCHANGE_MINS = \\{[\\s\\S]*?\\n\\};/);
        if (!m) { console.error('INTERCHANGE_MINS block not found'); process.exit(1); }
        try {
            const fn = new Function(m[0] + '\\nreturn INTERCHANGE_MINS;');
            const I = fn();
            console.log(Object.keys(I).length);
        } catch (e) {
            console.error('Parse failed:', e.message); process.exit(2);
        }
    '''
    result = subprocess.run(['node', '-e', script, str(INDEX_HTML)],
                            capture_output=True, text=True)
    assert result.returncode == 0, (
        f'JS parse failed:\nstdout: {result.stdout}\nstderr: {result.stderr}'
    )
    n_stations = int(result.stdout.strip())
    assert n_stations >= 80, f'Suspiciously few stations: {n_stations}'


def test_interchange_block_has_no_duplicate_header():
    """Re-running --apply on a file with a pre-existing header should
    not leave duplicate header blocks. Guards against the regression
    we hit during initial development."""
    _skip_if_no_index()
    html = INDEX_HTML.read_text(encoding='utf-8')
    count = html.count('Auto-generated by build_interchanges')
    assert count == 1, (
        f'Expected exactly 1 generated header in index.html, found {count}. '
        f'Re-running --apply may have piled up duplicate headers.'
    )


def test_known_interchanges_have_expected_values():
    """A handful of well-known cross-platform interchanges must remain
    1 minute. If these regress, the cross-platform declarations in
    overrides.py have been broken."""
    _skip_if_no_index()
    _, interchange = game_data.load_game_data(INDEX_HTML)

    known_one_minute = [
        ('Mile End', 'Central|District'),
        ('Westminster', 'Circle|District'),
        ('Sloane Square', 'Circle|District'),
        ('Mansion House', 'Circle|District'),
        ('Bank', 'Circle|District'),  # Linked-station: routed via Monument
    ]
    for stn, pair in known_one_minute:
        val = interchange.get(stn, {}).get(pair)
        # Bank/Monument linking means the value might appear at the
        # other station. Skip if not present rather than fail.
        if val is None:
            continue
        assert val <= 2, f'{stn} [{pair}] = {val}; expected ≤ 2 (cross-platform)'


def test_branch_split_pairs_preserved():
    """Same-line branch-split interchanges (Whitechapel Elizabeth|Elizabeth
    etc.) must remain in the output even though the parser would otherwise
    drop X|X pairs. Guards against the bug we caught during review."""
    _skip_if_no_index()
    _, interchange = game_data.load_game_data(INDEX_HTML)

    branch_splits = [
        ('Whitechapel', 'Elizabeth|Elizabeth'),
        ('Woodford', 'Central|Central'),
        ('Heathrow Terminals 2&3', 'Elizabeth|Elizabeth'),
    ]
    for stn, pair in branch_splits:
        assert pair in interchange.get(stn, {}), (
            f'{stn} [{pair}] missing from INTERCHANGE_MINS — branch-split '
            f'pairs must be preserved.'
        )


def test_freeze_in_today_puzzle_matches_generate_today():
    """The list of frozen daily puzzles in todayPuzzle() must match the
    list in generate-today.mjs::pickStations. If they diverge, the cron
    publishes today.json with one pair and the browser serves another."""
    _skip_if_no_index()
    GEN_MJS = ROOT / 'generate-today.mjs'
    if not GEN_MJS.exists():
        pytest.skip('generate-today.mjs not present')

    html = INDEX_HTML.read_text(encoding='utf-8')
    mjs = GEN_MJS.read_text(encoding='utf-8')

    # Each freeze is two lines: a date check and the station pair.
    # We just check that any date in todayPuzzle's freeze block also
    # appears in generate-today.mjs's pickStations.
    html_dates = set(re.findall(r"date === '(\d{4}-\d{2}-\d{2})'", html))
    mjs_dates = set(re.findall(r"dateStr === '(\d{4}-\d{2}-\d{2})'", mjs))
    only_in_html = html_dates - mjs_dates
    only_in_mjs = mjs_dates - html_dates
    assert not only_in_html, (
        f'Dates frozen in index.html but missing from generate-today.mjs: '
        f'{sorted(only_in_html)}'
    )
    assert not only_in_mjs, (
        f'Dates frozen in generate-today.mjs but missing from index.html: '
        f'{sorted(only_in_mjs)}'
    )
