"""Write INTERCHANGE_MINS back as a JS object literal block.

Output uses double-quoted keys throughout for consistency and to avoid
backslash-escaping apostrophes (e.g. "St. James's Park"). The pair keys
themselves never contain quotes or backslashes so they're safe in either
form, but we use double quotes everywhere for uniformity.
"""

from datetime import date
from pathlib import Path
from typing import Dict


def format_interchange_block(
    measured: Dict[str, Dict[str, int]],
    source_note: str = 'TfL Stop Structure API',
) -> str:
    """Render the full `const INTERCHANGE_MINS = { ... };` block as a string.

    The output begins with a blank line so that, when spliced back into a
    file via replace_in_html(), there's a visual separator between the
    previous block (typically `const PLATFORM_GROUPS = { ... };`) and the
    interchange header. The walk-back logic in replace_in_html strips any
    leading blank line in the file so re-runs don't accumulate them.
    """
    lines = [
        '',
        '// ── Interchange times (minutes, walking-only) ────────────────────────────────',
        '// Bank/Monument cross-complex pairs are duplicated under both stations so',
        '// interchangeTime() works regardless of which station is queried. When',
        '// platforms are shared (see PLATFORM_GROUPS), a single entry under one',
        '// display line implicitly covers all lines in that group.',
        '//',
        '// Auto-generated by build_interchanges. Do not edit manually.',
        f'// Source: {source_note} — {date.today().isoformat()}',
        '// Regenerate with: python3 -m build_interchanges',
        '',
        'const INTERCHANGE_MINS = {',
    ]
    for stn, pairs in sorted(measured.items()):
        if not pairs:
            continue
        # Always double-quote station keys for consistency.
        lines.append(f'  "{_escape_js(stn)}": {{')
        for pair, mins in sorted(pairs.items()):
            lines.append(f'    "{pair}": {mins},')
        lines.append('  },')
    lines.append('};')
    return '\n'.join(lines)


def _escape_js(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"')


def write_standalone_js(
    measured: Dict[str, Dict[str, int]],
    path: Path,
    source_note: str = 'TfL Stop Structure API',
) -> None:
    """Write the JS block as a standalone .js file (for diffing / review)."""
    body = format_interchange_block(measured, source_note)
    path.write_text(body + '\n', encoding='utf-8')


def replace_in_html(
    html_path: Path,
    measured: Dict[str, Dict[str, int]],
    source_note: str = 'TfL Stop Structure API',
) -> None:
    """Replace the existing INTERCHANGE_MINS block in index.html in place.

    Preserves everything outside the `const INTERCHANGE_MINS = { ... };`
    block exactly. Raises ValueError if the block can't be located.
    """
    html = html_path.read_text(encoding='utf-8')
    start = html.find('const INTERCHANGE_MINS = {')
    if start == -1:
        raise ValueError('const INTERCHANGE_MINS not found in HTML')

    # Walk back over any preceding auto-generated comment block so re-runs
    # don't pile up duplicate headers. The header includes both the leading
    # "Interchange times..." human comment and the auto-generated metadata.
    # We stop at the first line that isn't part of either block.
    GENERATED_PREFIXES = (
        '// ── Interchange times',
        '// Bank/Monument cross-complex pairs',
        '// interchangeTime() works regardless',
        '// platforms are shared',
        '// display line implicitly covers',
        '//',
        '// Auto-generated by build_interchanges',
        '// Source: TfL Stop Structure API',
        '// Regenerate with: python3 -m build_interchanges',
    )
    cursor = start
    while cursor > 0:
        prev_newline = html.rfind('\n', 0, cursor - 1)
        if prev_newline == -1:
            break
        prev_line = html[prev_newline + 1:cursor].rstrip('\n')
        stripped = prev_line.strip()
        if stripped == '' or stripped.startswith(GENERATED_PREFIXES):
            cursor = prev_newline + 1
        else:
            break
    start = cursor

    # Find matching '};' at the end of the block by brace counting.
    block_start = html.index('{', start)
    depth = 0
    end_brace = None
    for i in range(block_start, len(html)):
        ch = html[i]
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                end_brace = i
                break
    if end_brace is None:
        raise ValueError('Unbalanced braces in INTERCHANGE_MINS')

    # Walk forward to include the trailing `;` and newline.
    end = end_brace + 1
    if end < len(html) and html[end] == ';':
        end += 1

    new_block = format_interchange_block(measured, source_note)
    new_html = html[:start] + new_block + html[end:]
    html_path.write_text(new_html, encoding='utf-8')
